version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unused

  settings:
    errcheck:
      ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy

  exclusions:
    # exclude-dirs (from v1) seem to not have a direct equivalent in the snippet,
    # but maybe they go under 'exclusions' or 'run'?
    # Some results said 'run.skip-dirs' is gone.
    # We will try to rely on default ignores or .gitignore for directories for now.
    
    rules:
      - path: _test\.go
        linters:
          - dupl
