version: 2

run:
  tests: true
  skip-dirs:
    - bin
    - docs
    - example

linters-settings:
  errcheck:
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unused
  
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
