version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unused

  # settings:
    # errcheck:
    #   ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
