version: "2"

run:
  tests: true

issues:
  exclude-dirs:
    - bin
    - docs
    - example
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unused
  # linters-settings is deprecated/removed in v2 schema or handled differently.
  # For now, we rely on default settings or user can migrate properly if needed.
  # errcheck:
  #   ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy
