package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/roneli/fastgql/examples/json/graph/generated"
	"github.com/roneli/fastgql/examples/json/graph/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, limit *int, offset *int, orderBy []*model.ProductOrdering, filter *model.ProductFilterInput) ([]*model.Product, error) {
	var data []*model.Product
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// ProductsAggregate is the resolver for the _productsAggregate field.
func (r *queryResolver) ProductsAggregate(ctx context.Context, groupBy []model.ProductGroupBy, filter *model.ProductFilterInput) ([]*model.ProductsAggregate, error) {
	var data []*model.ProductsAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
