// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BooleanComparator struct {
	Eq     *bool `json:"eq,omitempty" db:"eq"`
	Neq    *bool `json:"neq,omitempty" db:"neq"`
	IsNull *bool `json:"isNull,omitempty" db:"is_null"`
}

type BooleanListComparator struct {
	Eq        []*bool `json:"eq,omitempty" db:"eq"`
	Neq       []*bool `json:"neq,omitempty" db:"neq"`
	Contains  []*bool `json:"contains,omitempty" db:"contains"`
	Contained []*bool `json:"contained,omitempty" db:"contained"`
	Overlap   []*bool `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool   `json:"isNull,omitempty" db:"is_null"`
}

type FloatComparator struct {
	Eq     *float64 `json:"eq,omitempty" db:"eq"`
	Neq    *float64 `json:"neq,omitempty" db:"neq"`
	Gt     *float64 `json:"gt,omitempty" db:"gt"`
	Gte    *float64 `json:"gte,omitempty" db:"gte"`
	Lt     *float64 `json:"lt,omitempty" db:"lt"`
	Lte    *float64 `json:"lte,omitempty" db:"lte"`
	IsNull *bool    `json:"isNull,omitempty" db:"is_null"`
}

type FloatListComparator struct {
	Eq        []*float64 `json:"eq,omitempty" db:"eq"`
	Neq       []*float64 `json:"neq,omitempty" db:"neq"`
	Contains  []*float64 `json:"contains,omitempty" db:"contains"`
	Contained []*float64 `json:"contained,omitempty" db:"contained"`
	Overlap   []*float64 `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool      `json:"isNull,omitempty" db:"is_null"`
}

type IntComparator struct {
	Eq     *int  `json:"eq,omitempty" db:"eq"`
	Neq    *int  `json:"neq,omitempty" db:"neq"`
	Gt     *int  `json:"gt,omitempty" db:"gt"`
	Gte    *int  `json:"gte,omitempty" db:"gte"`
	Lt     *int  `json:"lt,omitempty" db:"lt"`
	Lte    *int  `json:"lte,omitempty" db:"lte"`
	IsNull *bool `json:"isNull,omitempty" db:"is_null"`
}

type IntListComparator struct {
	Eq        []*int `json:"eq,omitempty" db:"eq"`
	Neq       []*int `json:"neq,omitempty" db:"neq"`
	Contains  []*int `json:"contains,omitempty" db:"contains"`
	Contained []*int `json:"contained,omitempty" db:"contained"`
	Overlap   []*int `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool  `json:"isNull,omitempty" db:"is_null"`
}

type Person struct {
	Name *string `json:"name,omitempty" db:"name"`
}

type Query struct {
}

type StringComparator struct {
	Eq               *string   `json:"eq,omitempty" db:"eq"`
	Neq              *string   `json:"neq,omitempty" db:"neq"`
	Contains         []*string `json:"contains,omitempty" db:"contains"`
	NotContains      []*string `json:"notContains,omitempty" db:"not_contains"`
	Like             *string   `json:"like,omitempty" db:"like"`
	Ilike            *string   `json:"ilike,omitempty" db:"ilike"`
	Suffix           *string   `json:"suffix,omitempty" db:"suffix"`
	Prefix           *string   `json:"prefix,omitempty" db:"prefix"`
	IsNull           *bool     `json:"isNull,omitempty" db:"is_null"`
	MyCustomOperator string    `json:"myCustomOperator" db:"my_custom_operator"`
}

type StringListComparator struct {
	Eq          []*string `json:"eq,omitempty" db:"eq"`
	Neq         []*string `json:"neq,omitempty" db:"neq"`
	Contains    []*string `json:"contains,omitempty" db:"contains"`
	ContainedBy []*string `json:"containedBy,omitempty" db:"contained_by"`
	Overlap     []*string `json:"overlap,omitempty" db:"overlap"`
	IsNull      *bool     `json:"isNull,omitempty" db:"is_null"`
}

type User struct {
	Name               *string `json:"name,omitempty" db:"name"`
	Age                *int    `json:"age,omitempty" db:"age"`
	SomeInnerValue     *User   `json:"someInnerValue,omitempty" db:"some_inner_value"`
	SomeInnerValueList []*User `json:"someInnerValueList,omitempty" db:"some_inner_value_list"`
}

type UserFilterInput struct {
	Name               *StringComparator `json:"name,omitempty" db:"name"`
	Age                *IntComparator    `json:"age,omitempty" db:"age"`
	SomeInnerValue     *UserFilterInput  `json:"someInnerValue,omitempty" db:"some_inner_value"`
	SomeInnerValueList *UserFilterInput  `json:"someInnerValueList,omitempty" db:"some_inner_value_list"`
	// Logical AND of FilterInput
	And []*UserFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*UserFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *UserFilterInput `json:"NOT,omitempty" db:"not"`
}

// Ordering for User
type UserOrdering struct {
	// Order User by name
	Name *OrderingTypes `json:"name,omitempty" db:"name"`
	// Order User by age
	Age *OrderingTypes `json:"age,omitempty" db:"age"`
}

// Aggregate User
type UsersAggregate struct {
	// Group
	Group map[string]any `json:"group,omitempty" db:"group"`
	// Count results
	Count int `json:"count" db:"count"`
	// Max Aggregate
	Max *UserMax `json:"max" db:"max"`
	// Min Aggregate
	Min *UserMin `json:"min" db:"min"`
	// Avg Aggregate
	Avg *UserAvg `json:"avg" db:"avg"`
	// Sum Aggregate
	Sum *UserSum `json:"sum" db:"sum"`
}

// Ordering for UsersAggregate
type UsersAggregateOrdering struct {
	// Order UsersAggregate by group
	Group *OrderingTypes `json:"group,omitempty" db:"group"`
	// Order UsersAggregate by count
	Count *OrderingTypes `json:"count,omitempty" db:"count"`
}

// Aggregate UsersAggregate
type UsersAggregatesAggregate struct {
	// Group
	Group map[string]any `json:"group,omitempty" db:"group"`
	// Count results
	Count int `json:"count" db:"count"`
	// Max Aggregate
	Max *UsersAggregateMax `json:"max" db:"max"`
	// Min Aggregate
	Min *UsersAggregateMin `json:"min" db:"min"`
	// Avg Aggregate
	Avg *UsersAggregateAvg `json:"avg" db:"avg"`
	// Sum Aggregate
	Sum *UsersAggregateSum `json:"sum" db:"sum"`
}

type AggregateResult struct {
	Count int `json:"count" db:"count"`
}

// avg Aggregate
type UserAvg struct {
	// Compute the avg for age
	Age float64 `json:"age" db:"age"`
}

// max Aggregate
type UserMax struct {
	// Compute the max for name
	Name string `json:"name" db:"name"`
	// Compute the max for age
	Age int `json:"age" db:"age"`
}

// min Aggregate
type UserMin struct {
	// Compute the min for name
	Name string `json:"name" db:"name"`
	// Compute the min for age
	Age int `json:"age" db:"age"`
}

// sum Aggregate
type UserSum struct {
	// Compute the sum for age
	Age float64 `json:"age" db:"age"`
}

// avg Aggregate
type UsersAggregateAvg struct {
	// Compute the avg for count
	Count float64 `json:"count" db:"count"`
}

// max Aggregate
type UsersAggregateMax struct {
	// Compute the max for count
	Count int `json:"count" db:"count"`
}

// min Aggregate
type UsersAggregateMin struct {
	// Compute the min for count
	Count int `json:"count" db:"count"`
}

// sum Aggregate
type UsersAggregateSum struct {
	// Compute the sum for count
	Count float64 `json:"count" db:"count"`
}

// Group by User
type UserGroupBy string

const (
	// Group by name
	UserGroupByName UserGroupBy = "NAME"
	// Group by age
	UserGroupByAge UserGroupBy = "AGE"
)

var AllUserGroupBy = []UserGroupBy{
	UserGroupByName,
	UserGroupByAge,
}

func (e UserGroupBy) IsValid() bool {
	switch e {
	case UserGroupByName, UserGroupByAge:
		return true
	}
	return false
}

func (e UserGroupBy) String() string {
	return string(e)
}

func (e *UserGroupBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserGroupBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserGroupBy", str)
	}
	return nil
}

func (e UserGroupBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserGroupBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserGroupBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Group by UsersAggregate
type UsersAggregateGroupBy string

const (
	// Group by group
	UsersAggregateGroupByGroup UsersAggregateGroupBy = "GROUP"
	// Group by count
	UsersAggregateGroupByCount UsersAggregateGroupBy = "COUNT"
)

var AllUsersAggregateGroupBy = []UsersAggregateGroupBy{
	UsersAggregateGroupByGroup,
	UsersAggregateGroupByCount,
}

func (e UsersAggregateGroupBy) IsValid() bool {
	switch e {
	case UsersAggregateGroupByGroup, UsersAggregateGroupByCount:
		return true
	}
	return false
}

func (e UsersAggregateGroupBy) String() string {
	return string(e)
}

func (e *UsersAggregateGroupBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UsersAggregateGroupBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UsersAggregateGroupBy", str)
	}
	return nil
}

func (e UsersAggregateGroupBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UsersAggregateGroupBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UsersAggregateGroupBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderingTypes string

const (
	OrderingTypesAsc           OrderingTypes = "ASC"
	OrderingTypesDesc          OrderingTypes = "DESC"
	OrderingTypesAscNullFirst  OrderingTypes = "ASC_NULL_FIRST"
	OrderingTypesDescNullFirst OrderingTypes = "DESC_NULL_FIRST"
	OrderingTypesAscNullLast   OrderingTypes = "ASC_NULL_LAST"
	OrderingTypesDescNullLast  OrderingTypes = "DESC_NULL_LAST"
)

var AllOrderingTypes = []OrderingTypes{
	OrderingTypesAsc,
	OrderingTypesDesc,
	OrderingTypesAscNullFirst,
	OrderingTypesDescNullFirst,
	OrderingTypesAscNullLast,
	OrderingTypesDescNullLast,
}

func (e OrderingTypes) IsValid() bool {
	switch e {
	case OrderingTypesAsc, OrderingTypesDesc, OrderingTypesAscNullFirst, OrderingTypesDescNullFirst, OrderingTypesAscNullLast, OrderingTypesDescNullLast:
		return true
	}
	return false
}

func (e OrderingTypes) String() string {
	return string(e)
}

func (e *OrderingTypes) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderingTypes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _OrderingTypes", str)
	}
	return nil
}

func (e OrderingTypes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderingTypes) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderingTypes) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RelationType string

const (
	RelationTypeOneToOne   RelationType = "ONE_TO_ONE"
	RelationTypeOneToMany  RelationType = "ONE_TO_MANY"
	RelationTypeManyToMany RelationType = "MANY_TO_MANY"
)

var AllRelationType = []RelationType{
	RelationTypeOneToOne,
	RelationTypeOneToMany,
	RelationTypeManyToMany,
}

func (e RelationType) IsValid() bool {
	switch e {
	case RelationTypeOneToOne, RelationTypeOneToMany, RelationTypeManyToMany:
		return true
	}
	return false
}

func (e RelationType) String() string {
	return string(e)
}

func (e *RelationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _relationType", str)
	}
	return nil
}

func (e RelationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RelationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RelationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
