package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/roneli/fastgql/pkg/execution/__test__/graph/model"
)

// CreatePosts is the resolver for the createPosts field.
func (r *mutationResolver) CreatePosts(ctx context.Context, inputs []model1.CreatePostInput) (*model1.PostsPayload, error) {
	var data model.PostsPayload
	if err := r.Executor.Execute(ctx, &data); err != nil {
		return nil, err
	}
	return &data, nil
}

// DeletePosts is the resolver for the deletePosts field.
func (r *mutationResolver) DeletePosts(ctx context.Context, cascade *bool, filter *model1.PostFilterInput) (*model1.PostsPayload, error) {
	var data model.PostsPayload
	if err := r.Executor.Execute(ctx, &data); err != nil {
		return nil, err
	}
	return &data, nil
}

// UpdatePosts is the resolver for the updatePosts field.
func (r *mutationResolver) UpdatePosts(ctx context.Context, input model1.UpdatePostInput, filter *model1.PostFilterInput) (*model1.PostsPayload, error) {
	var data model.PostsPayload
	if err := r.Executor.Execute(ctx, &data); err != nil {
		return nil, err
	}
	return &data, nil
}

// Mutation returns generated1.MutationResolver implementation.
func (r *Resolver) Mutation() generated1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
