package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"reflect"

	"github.com/roneli/fastgql/examples/interface/graph/generated"
	"github.com/roneli/fastgql/examples/interface/graph/model"
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int, orderBy []*model.PostOrdering, filter *model.PostFilterInput) ([]*model.Post, error) {
	var data []*model.Post
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int, orderBy []*model.UserOrdering, filter *model.UserFilterInput) ([]*model.User, error) {
	var data []*model.User
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, limit *int, offset *int, orderBy []*model.CategoryOrdering, filter *model.CategoryFilterInput) ([]*model.Category, error) {
	var data []*model.Category
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Animals is the resolver for the animals field.
func (r *queryResolver) Animals(ctx context.Context, limit *int, offset *int, orderBy []*model.AnimalOrdering, filter *model.AnimalFilterInput) ([]model.Animal, error) {
	var data []model.Animal
	if err := r.Executor.QueryWithTypes(ctx, &data, map[string]reflect.Type{
		"Cat": reflect.TypeOf(model.Cat{}),
		"Dog": reflect.TypeOf(model.Dog{})}, "type"); err != nil {
		return nil, err
	}
	return data, nil
}

// PostsAggregate is the resolver for the _postsAggregate field.
func (r *queryResolver) PostsAggregate(ctx context.Context, groupBy []model.PostGroupBy, filter *model.PostFilterInput, limit *int, offset *int, orderBy []*model.PostsAggregateOrdering) ([]*model.PostsAggregate, error) {
	var data []*model.PostsAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// UsersAggregate is the resolver for the _usersAggregate field.
func (r *queryResolver) UsersAggregate(ctx context.Context, groupBy []model.UserGroupBy, filter *model.UserFilterInput, limit *int, offset *int, orderBy []*model.UsersAggregateOrdering) ([]*model.UsersAggregate, error) {
	var data []*model.UsersAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// CategoriesAggregate is the resolver for the _categoriesAggregate field.
func (r *queryResolver) CategoriesAggregate(ctx context.Context, groupBy []model.CategoryGroupBy, filter *model.CategoryFilterInput, limit *int, offset *int, orderBy []*model.CategoriesAggregateOrdering) ([]*model.CategoriesAggregate, error) {
	var data []*model.CategoriesAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// AnimalsAggregate is the resolver for the _animalsAggregate field.
func (r *queryResolver) AnimalsAggregate(ctx context.Context, groupBy []model.AnimalGroupBy, filter *model.AnimalFilterInput, limit *int, offset *int, orderBy []*model.AnimalsAggregateOrdering) ([]*model.AnimalsAggregate, error) {
	var data []*model.AnimalsAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
