// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/roneli/fastgql/examples/interface/graph/model"
)

type Dimensions struct {
	Width  *float64 `json:"width,omitempty" db:"width"`
	Height *float64 `json:"height,omitempty" db:"height"`
	Depth  *float64 `json:"depth,omitempty" db:"depth"`
}

// Filter input for JSON type Dimensions
type DimensionsFilterInput struct {
	Width  *model.FloatComparator `json:"width,omitempty" db:"width"`
	Height *model.FloatComparator `json:"height,omitempty" db:"height"`
	Depth  *model.FloatComparator `json:"depth,omitempty" db:"depth"`
	// Logical AND of FilterInput
	And []*DimensionsFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*DimensionsFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *DimensionsFilterInput `json:"NOT,omitempty" db:"not"`
}

type IDComparator struct {
	Eq     *string `json:"eq,omitempty" db:"eq"`
	Neq    *string `json:"neq,omitempty" db:"neq"`
	IsNull *bool   `json:"isNull,omitempty" db:"is_null"`
}

type MapComparator struct {
	Contains map[string]any      `json:"contains,omitempty" db:"contains"`
	Where    []*MapPathCondition `json:"where,omitempty" db:"where"`
	WhereAny []*MapPathCondition `json:"whereAny,omitempty" db:"where_any"`
	IsNull   *bool               `json:"isNull,omitempty" db:"is_null"`
}

type MapPathCondition struct {
	Path   string   `json:"path" db:"path"`
	Eq     *string  `json:"eq,omitempty" db:"eq"`
	Neq    *string  `json:"neq,omitempty" db:"neq"`
	Gt     *float64 `json:"gt,omitempty" db:"gt"`
	Gte    *float64 `json:"gte,omitempty" db:"gte"`
	Lt     *float64 `json:"lt,omitempty" db:"lt"`
	Lte    *float64 `json:"lte,omitempty" db:"lte"`
	Like   *string  `json:"like,omitempty" db:"like"`
	IsNull *bool    `json:"isNull,omitempty" db:"is_null"`
}

type Product struct {
	ID         int                `json:"id" db:"id"`
	Name       string             `json:"name" db:"name"`
	Attributes *ProductAttributes `json:"attributes,omitempty" db:"attributes"`
	Metadata   map[string]any     `json:"metadata,omitempty" db:"metadata"`
}

type ProductAttributes struct {
	Color   *string         `json:"color,omitempty" db:"color"`
	Size    *int            `json:"size,omitempty" db:"size"`
	Tags    []*string       `json:"tags,omitempty" db:"tags"`
	Details *ProductDetails `json:"details,omitempty" db:"details"`
	Specs   *Specs          `json:"specs,omitempty" db:"specs"`
}

// Filter input for JSON type ProductAttributes
type ProductAttributesFilterInput struct {
	Color   *model.StringComparator     `json:"color,omitempty" db:"color"`
	Size    *model.IntComparator        `json:"size,omitempty" db:"size"`
	Tags    *model.StringListComparator `json:"tags,omitempty" db:"tags"`
	Details *ProductDetailsFilterInput  `json:"details,omitempty" db:"details"`
	Specs   *SpecsFilterInput           `json:"specs,omitempty" db:"specs"`
	// Logical AND of FilterInput
	And []*ProductAttributesFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*ProductAttributesFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *ProductAttributesFilterInput `json:"NOT,omitempty" db:"not"`
}

type ProductDetails struct {
	Manufacturer *string       `json:"manufacturer,omitempty" db:"manufacturer"`
	Model        *string       `json:"model,omitempty" db:"model"`
	Warranty     *WarrantyInfo `json:"warranty,omitempty" db:"warranty"`
}

// Filter input for JSON type ProductDetails
type ProductDetailsFilterInput struct {
	Manufacturer *model.StringComparator  `json:"manufacturer,omitempty" db:"manufacturer"`
	Model        *model.StringComparator  `json:"model,omitempty" db:"model"`
	Warranty     *WarrantyInfoFilterInput `json:"warranty,omitempty" db:"warranty"`
	// Logical AND of FilterInput
	And []*ProductDetailsFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*ProductDetailsFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *ProductDetailsFilterInput `json:"NOT,omitempty" db:"not"`
}

type ProductFilterInput struct {
	ID         *model.IntComparator          `json:"id,omitempty" db:"id"`
	Name       *model.StringComparator       `json:"name,omitempty" db:"name"`
	Attributes *ProductAttributesFilterInput `json:"attributes,omitempty" db:"attributes"`
	Metadata   *MapComparator                `json:"metadata,omitempty" db:"metadata"`
	// Logical AND of FilterInput
	And []*ProductFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*ProductFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *ProductFilterInput `json:"NOT,omitempty" db:"not"`
}

// Ordering for Product
type ProductOrdering struct {
	// Order Product by id
	ID *model.OrderingTypes `json:"id,omitempty" db:"id"`
	// Order Product by name
	Name *model.OrderingTypes `json:"name,omitempty" db:"name"`
	// Order Product by metadata
	Metadata *model.OrderingTypes `json:"metadata,omitempty" db:"metadata"`
}

// Aggregate Product
type ProductsAggregate struct {
	// Group
	Group map[string]any `json:"group,omitempty" db:"group"`
	// Count results
	Count int `json:"count" db:"count"`
	// Max Aggregate
	Max *ProductMax `json:"max" db:"max"`
	// Min Aggregate
	Min *ProductMin `json:"min" db:"min"`
	// Avg Aggregate
	Avg *ProductAvg `json:"avg" db:"avg"`
	// Sum Aggregate
	Sum *ProductSum `json:"sum" db:"sum"`
}

type Specs struct {
	Weight     *float64    `json:"weight,omitempty" db:"weight"`
	Dimensions *Dimensions `json:"dimensions,omitempty" db:"dimensions"`
}

// Filter input for JSON type Specs
type SpecsFilterInput struct {
	Weight     *model.FloatComparator `json:"weight,omitempty" db:"weight"`
	Dimensions *DimensionsFilterInput `json:"dimensions,omitempty" db:"dimensions"`
	// Logical AND of FilterInput
	And []*SpecsFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*SpecsFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *SpecsFilterInput `json:"NOT,omitempty" db:"not"`
}

type WarrantyInfo struct {
	Years    *int    `json:"years,omitempty" db:"years"`
	Provider *string `json:"provider,omitempty" db:"provider"`
}

// Filter input for JSON type WarrantyInfo
type WarrantyInfoFilterInput struct {
	Years    *model.IntComparator    `json:"years,omitempty" db:"years"`
	Provider *model.StringComparator `json:"provider,omitempty" db:"provider"`
	// Logical AND of FilterInput
	And []*WarrantyInfoFilterInput `json:"AND,omitempty" db:"and"`
	// Logical OR of FilterInput
	Or []*WarrantyInfoFilterInput `json:"OR,omitempty" db:"or"`
	// Logical NOT of FilterInput
	Not *WarrantyInfoFilterInput `json:"NOT,omitempty" db:"not"`
}

// avg Aggregate
type ProductAvg struct {
	// Compute the avg for id
	ID float64 `json:"id" db:"id"`
}

// max Aggregate
type ProductMax struct {
	// Compute the max for id
	ID int `json:"id" db:"id"`
	// Compute the max for name
	Name string `json:"name" db:"name"`
}

// min Aggregate
type ProductMin struct {
	// Compute the min for id
	ID int `json:"id" db:"id"`
	// Compute the min for name
	Name string `json:"name" db:"name"`
}

// sum Aggregate
type ProductSum struct {
	// Compute the sum for id
	ID float64 `json:"id" db:"id"`
}

// Group by Product
type ProductGroupBy string

const (
	// Group by id
	ProductGroupByID ProductGroupBy = "ID"
	// Group by name
	ProductGroupByName ProductGroupBy = "NAME"
	// Group by metadata
	ProductGroupByMetadata ProductGroupBy = "METADATA"
)

var AllProductGroupBy = []ProductGroupBy{
	ProductGroupByID,
	ProductGroupByName,
	ProductGroupByMetadata,
}

func (e ProductGroupBy) IsValid() bool {
	switch e {
	case ProductGroupByID, ProductGroupByName, ProductGroupByMetadata:
		return true
	}
	return false
}

func (e ProductGroupBy) String() string {
	return string(e)
}

func (e *ProductGroupBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductGroupBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductGroupBy", str)
	}
	return nil
}

func (e ProductGroupBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductGroupBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductGroupBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
