package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/roneli/fastgql/examples/custom_operator/graph/generated"
	"github.com/roneli/fastgql/examples/custom_operator/graph/model"
)

// Person is the resolver for the person field.
func (r *queryResolver) Person(ctx context.Context) (*model.Person, error) {
	var data *model.Person
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, limit *int, offset *int, orderBy []*model.UserOrdering, filter *model.UserFilterInput) ([]*model.User, error) {
	var data []*model.User
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// UserAggregate is the resolver for the _userAggregate field.
func (r *queryResolver) UserAggregate(ctx context.Context, groupBy []model.UserGroupBy, filter *model.UserFilterInput, limit *int, offset *int, orderBy []*model.UsersAggregateOrdering) ([]model.UsersAggregate, error) {
	var data []model.UsersAggregate
	if err := r.Executor.Query(ctx, &data); err != nil {
		return nil, err
	}
	return data, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
