// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type BooleanComparator struct {
	Eq     *bool `json:"eq,omitempty" db:"eq"`
	Neq    *bool `json:"neq,omitempty" db:"neq"`
	IsNull *bool `json:"isNull,omitempty" db:"isNull"`
}

type BooleanListComparator struct {
	Eq        []*bool `json:"eq,omitempty" db:"eq"`
	Neq       []*bool `json:"neq,omitempty" db:"neq"`
	Contains  []*bool `json:"contains,omitempty" db:"contains"`
	Contained []*bool `json:"contained,omitempty" db:"contained"`
	Overlap   []*bool `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool   `json:"isNull,omitempty" db:"isNull"`
}

type FloatComparator struct {
	Eq     *float64 `json:"eq,omitempty" db:"eq"`
	Neq    *float64 `json:"neq,omitempty" db:"neq"`
	Gt     *float64 `json:"gt,omitempty" db:"gt"`
	Gte    *float64 `json:"gte,omitempty" db:"gte"`
	Lt     *float64 `json:"lt,omitempty" db:"lt"`
	Lte    *float64 `json:"lte,omitempty" db:"lte"`
	IsNull *bool    `json:"isNull,omitempty" db:"isNull"`
}

type FloatListComparator struct {
	Eq        []*float64 `json:"eq,omitempty" db:"eq"`
	Neq       []*float64 `json:"neq,omitempty" db:"neq"`
	Contains  []*float64 `json:"contains,omitempty" db:"contains"`
	Contained []*float64 `json:"contained,omitempty" db:"contained"`
	Overlap   []*float64 `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool      `json:"isNull,omitempty" db:"isNull"`
}

type IntComparator struct {
	Eq     *int  `json:"eq,omitempty" db:"eq"`
	Neq    *int  `json:"neq,omitempty" db:"neq"`
	Gt     *int  `json:"gt,omitempty" db:"gt"`
	Gte    *int  `json:"gte,omitempty" db:"gte"`
	Lt     *int  `json:"lt,omitempty" db:"lt"`
	Lte    *int  `json:"lte,omitempty" db:"lte"`
	IsNull *bool `json:"isNull,omitempty" db:"isNull"`
}

type IntListComparator struct {
	Eq        []*int `json:"eq,omitempty" db:"eq"`
	Neq       []*int `json:"neq,omitempty" db:"neq"`
	Contains  []*int `json:"contains,omitempty" db:"contains"`
	Contained []*int `json:"contained,omitempty" db:"contained"`
	Overlap   []*int `json:"overlap,omitempty" db:"overlap"`
	IsNull    *bool  `json:"isNull,omitempty" db:"isNull"`
}

type Person struct {
	Name *string `json:"name,omitempty" db:"name"`
}

type StringComparator struct {
	Eq          *string   `json:"eq,omitempty" db:"eq"`
	Neq         *string   `json:"neq,omitempty" db:"neq"`
	Contains    []*string `json:"contains,omitempty" db:"contains"`
	NotContains []*string `json:"notContains,omitempty" db:"notContains"`
	Like        *string   `json:"like,omitempty" db:"like"`
	Ilike       *string   `json:"ilike,omitempty" db:"ilike"`
	Suffix      *string   `json:"suffix,omitempty" db:"suffix"`
	Prefix      *string   `json:"prefix,omitempty" db:"prefix"`
	IsNull      *bool     `json:"isNull,omitempty" db:"isNull"`
}

type StringListComparator struct {
	Eq          []*string `json:"eq,omitempty" db:"eq"`
	Neq         []*string `json:"neq,omitempty" db:"neq"`
	Contains    []*string `json:"contains,omitempty" db:"contains"`
	ContainedBy []*string `json:"containedBy,omitempty" db:"containedBy"`
	Overlap     []*string `json:"overlap,omitempty" db:"overlap"`
	IsNull      *bool     `json:"isNull,omitempty" db:"isNull"`
}

type User struct {
	Name *string `json:"name,omitempty" db:"name"`
	Age  *int    `json:"age,omitempty" db:"age"`
}

// max aggregator for User
type UserMin struct {
	// Compute the maxiumum for name
	Name string `json:"name" db:"name"`
	// Compute the maxiumum for age
	Age int `json:"age" db:"age"`
}

// Ordering for User
type UserOrdering struct {
	// Order User by name
	Name *OrderingTypes `json:"name,omitempty" db:"name"`
	// Order User by age
	Age *OrderingTypes `json:"age,omitempty" db:"age"`
}

// Aggregate User
type UsersAggregate struct {
	// Count results
	Count int `json:"count" db:"count"`
	// Computes the maximum of the non-null input values.
	Max *UserMin `json:"max,omitempty" db:"max"`
	// Computes the minimum of the non-null input values.
	Min *UserMin `json:"min,omitempty" db:"min"`
}

type AggregateResult struct {
	Count int `json:"count" db:"count"`
}

type OrderingTypes string

const (
	OrderingTypesAsc           OrderingTypes = "ASC"
	OrderingTypesDesc          OrderingTypes = "DESC"
	OrderingTypesAscNullFirst  OrderingTypes = "ASC_NULL_FIRST"
	OrderingTypesDescNullFirst OrderingTypes = "DESC_NULL_FIRST"
)

var AllOrderingTypes = []OrderingTypes{
	OrderingTypesAsc,
	OrderingTypesDesc,
	OrderingTypesAscNullFirst,
	OrderingTypesDescNullFirst,
}

func (e OrderingTypes) IsValid() bool {
	switch e {
	case OrderingTypesAsc, OrderingTypesDesc, OrderingTypesAscNullFirst, OrderingTypesDescNullFirst:
		return true
	}
	return false
}

func (e OrderingTypes) String() string {
	return string(e)
}

func (e *OrderingTypes) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderingTypes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _OrderingTypes", str)
	}
	return nil
}

func (e OrderingTypes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RelationType string

const (
	RelationTypeOneToOne   RelationType = "ONE_TO_ONE"
	RelationTypeOneToMany  RelationType = "ONE_TO_MANY"
	RelationTypeManyToMany RelationType = "MANY_TO_MANY"
)

var AllRelationType = []RelationType{
	RelationTypeOneToOne,
	RelationTypeOneToMany,
	RelationTypeManyToMany,
}

func (e RelationType) IsValid() bool {
	switch e {
	case RelationTypeOneToOne, RelationTypeOneToMany, RelationTypeManyToMany:
		return true
	}
	return false
}

func (e RelationType) String() string {
	return string(e)
}

func (e *RelationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _relationType", str)
	}
	return nil
}

func (e RelationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
