// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Actor struct {
	ActorID    int    `json:"actorId" db:"actorId"`
	FirstName  string `json:"firstName" db:"firstName"`
	LastName   string `json:"LastName" db:"LastName"`
	LastUpdate string `json:"LastUpdate" db:"LastUpdate"`
}

type ActorFilterInput struct {
	ActorID    *IntComparator    `json:"actorId" db:"actorId"`
	FirstName  *StringComparator `json:"firstName" db:"firstName"`
	LastName   *StringComparator `json:"LastName" db:"LastName"`
	LastUpdate *StringComparator `json:"LastUpdate" db:"LastUpdate"`
	// Logical AND of FilterInput
	And []*ActorFilterInput `json:"AND" db:"AND"`
	// Logical OR of FilterInput
	Or []*ActorFilterInput `json:"OR" db:"OR"`
	// Logical NOT of FilterInput
	Not *ActorFilterInput `json:"NOT" db:"NOT"`
}

// max aggregator for Actor
type ActorMin struct {
	// Compute the maxiumum for actorId
	ActorID int `json:"actorId" db:"actorId"`
	// Compute the maxiumum for firstName
	FirstName int `json:"firstName" db:"firstName"`
	// Compute the maxiumum for LastName
	LastName int `json:"LastName" db:"LastName"`
	// Compute the maxiumum for LastUpdate
	LastUpdate int `json:"LastUpdate" db:"LastUpdate"`
}

// Ordering for Actor
type ActorOrdering struct {
	// Order Actor by actorId
	ActorID *OrderingTypes `json:"actorId" db:"actorId"`
	// Order Actor by firstName
	FirstName *OrderingTypes `json:"firstName" db:"firstName"`
	// Order Actor by LastName
	LastName *OrderingTypes `json:"LastName" db:"LastName"`
	// Order Actor by LastUpdate
	LastUpdate *OrderingTypes `json:"LastUpdate" db:"LastUpdate"`
}

// Aggregate Actor
type ActorsAggregate struct {
	// Count results
	Count int `json:"count" db:"count"`
	// Computes the maximum of the non-null input values.
	Max *ActorMin `json:"max" db:"max"`
	// Computes the minimum of the non-null input values.
	Min *ActorMin `json:"min" db:"min"`
}

type BooleanComparator struct {
	Eq  *bool `json:"eq" db:"eq"`
	Neq *bool `json:"neq" db:"neq"`
}

type BooleanListComparator struct {
	Eq        []*bool `json:"eq" db:"eq"`
	Neq       []*bool `json:"neq" db:"neq"`
	Contains  []*bool `json:"contains" db:"contains"`
	Contained []*bool `json:"contained" db:"contained"`
	Overlap   []*bool `json:"overlap" db:"overlap"`
}

type IntComparator struct {
	Eq  *int `json:"eq" db:"eq"`
	Neq *int `json:"neq" db:"neq"`
	Gt  *int `json:"gt" db:"gt"`
	Gte *int `json:"gte" db:"gte"`
	Lt  *int `json:"lt" db:"lt"`
	Lte *int `json:"lte" db:"lte"`
}

type IntListComparator struct {
	Eq        []*int `json:"eq" db:"eq"`
	Neq       []*int `json:"neq" db:"neq"`
	Contains  []*int `json:"contains" db:"contains"`
	Contained []*int `json:"contained" db:"contained"`
	Overlap   []*int `json:"overlap" db:"overlap"`
}

type StringComparator struct {
	Eq          *string   `json:"eq" db:"eq"`
	Neq         *string   `json:"neq" db:"neq"`
	Contains    []*string `json:"contains" db:"contains"`
	NotContains []*string `json:"not_contains" db:"not_contains"`
	Like        *string   `json:"like" db:"like"`
	Ilike       *string   `json:"ilike" db:"ilike"`
	Suffix      *string   `json:"suffix" db:"suffix"`
	Prefix      *string   `json:"prefix" db:"prefix"`
}

type StringListComparator struct {
	Eq          []*string `json:"eq" db:"eq"`
	Neq         []*string `json:"neq" db:"neq"`
	Contains    []*string `json:"contains" db:"contains"`
	ContainedBy []*string `json:"containedBy" db:"containedBy"`
	Overlap     []*string `json:"overlap" db:"overlap"`
}

type AggregateResult struct {
	Count int `json:"count" db:"count"`
}

type OrderingTypes string

const (
	OrderingTypesAsc           OrderingTypes = "ASC"
	OrderingTypesDesc          OrderingTypes = "DESC"
	OrderingTypesAscNullFirst  OrderingTypes = "ASC_NULL_FIRST"
	OrderingTypesDescNullFirst OrderingTypes = "DESC_NULL_FIRST"
)

var AllOrderingTypes = []OrderingTypes{
	OrderingTypesAsc,
	OrderingTypesDesc,
	OrderingTypesAscNullFirst,
	OrderingTypesDescNullFirst,
}

func (e OrderingTypes) IsValid() bool {
	switch e {
	case OrderingTypesAsc, OrderingTypesDesc, OrderingTypesAscNullFirst, OrderingTypesDescNullFirst:
		return true
	}
	return false
}

func (e OrderingTypes) String() string {
	return string(e)
}

func (e *OrderingTypes) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderingTypes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _OrderingTypes", str)
	}
	return nil
}

func (e OrderingTypes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RelationType string

const (
	RelationTypeOneToOne   RelationType = "ONE_TO_ONE"
	RelationTypeOneToMany  RelationType = "ONE_TO_MANY"
	RelationTypeManyToMany RelationType = "MANY_TO_MANY"
)

var AllRelationType = []RelationType{
	RelationTypeOneToOne,
	RelationTypeOneToMany,
	RelationTypeManyToMany,
}

func (e RelationType) IsValid() bool {
	switch e {
	case RelationTypeOneToOne, RelationTypeOneToMany, RelationTypeManyToMany:
		return true
	}
	return false
}

func (e RelationType) String() string {
	return string(e)
}

func (e *RelationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid _relationType", str)
	}
	return nil
}

func (e RelationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
