name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: { go-version: 1.15 }
      - run: go mod download
      - run: .github/workflows/check-fmt.sh
      - run: .github/workflows/check-linting.sh
      - run: .github/workflows/check-generate.sh
